# Generated by Django 5.1.2 on 2024-11-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_budget_active_budget_title_transaction_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
