# Generated by Django 5.1.2 on 2024-11-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_transaction_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
