# Generated by Django 5.1.2 on 2025-02-16 15:48

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0007_alter_transaction_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DAASUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_agent', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=6)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('tenants.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('school', models.TextField(null=True)),
                ('termfees', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('Contact', 'cont'), ('Discussion', 'disc'), ('Appointment', 'app'), ('Decision', 'dec'), ('Agreement', 'agr')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('meetingdate', models.DateTimeField(null=True)),
                ('meetinglocation', models.TextField(null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
