# Generated by Django 5.1.2 on 2025-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daasuser',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='stage',
            field=models.CharField(choices=[('cont', 'Contact'), ('disc', 'Discussion'), ('app', 'Appointment'), ('dec', 'Decision'), ('agr', 'Agreement')], max_length=20),
        ),
    ]
