# Generated by Django 5.1.2 on 2025-02-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daas', '0002_alter_daasuser_code_alter_prospect_stage'),
        ('tenants', '0009_alter_budget_user_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='daasuser',
            name='code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='daasuser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tenants.user'),
        ),
    ]
