# Generated by Django 5.1.2 on 2025-02-16 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daas', '0003_rename_datetime_prospect_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daas.daasuser'),
        ),
    ]
