# Generated by Django 5.1.2 on 2025-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daas', '0007_alter_prospect_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
